pipeline {
    agent none
    stages {
        stage('Checkout') {
            agent {
                docker { image 'alpine/git' }
            }
            steps {
                // Clone the repository
                sh 'git clone https://github.com/Omkar-Patil16/Jenkins-Zero-To-Hero.git'
                // Navigate to the project directory
                dir('Jenkins-Zero-To-Hero/python') {
                    // Ensure the latest version is pulled
                    sh 'git pull origin main'
                }
            }
        }
        stage('Build') {
            agent {
                docker { image 'python:3.9-alpine' }
            }
            steps {
                dir('Jenkins-Zero-To-Hero/python') {
                    sh 'python --version'
                    sh 'pip install --user -r requirements.txt'
                }
            }
        }
        stage('Test') {
            agent {
                docker { image 'python:3.9-alpine' }
            }
            steps {
                dir('Jenkins-Zero-To-Hero/python') {
                    sh 'pytest'
                }
            }
        }
        stage('Deploy') {
            agent {
                docker { image 'docker:20.10.7' }
            }
            steps {
                script {
                    dir('Jenkins-Zero-To-Hero/python') {
                        def app = docker.build("my-python-app:${env.BUILD_ID}")
                        app.push()
                    }
                }
            }
        }
    }
}
